### ISSUE TITLE
Choose license

### ISSUE THREAD

**Issue by qurben** [csrdelft/orm#11]
Packagist requires us to choose a license (or mark as proprietary) in order for further updates to process.

> License "Unknown" is not a valid SPDX license identifier, see https://spdx.org/licenses/ if you use an open license.
If the software is closed-source, you may use "proprietary" as license.

**Comment by brussee** [comment]
https://spdx.org/licenses/BSD-3-Clause-No-Nuclear-License.html
of gewoon MIT?

**Comment by qurben** [comment]
Ik denk dat MIT hier het makkelijkst is. De BSD-3 no nuclear license is daarentegen wel geinig.

**Comment by qurben** [comment]
Fixed in #12
